defaults: &defaults
  rails_tutorial:
    homepage_url: "http://www.railstutorial.org/"
    help_url: "http://www.railstutorial.org/help"
    book_url: "http://www.railstutorial.org/book"

  mailer:
    email_from_address: "noreply@example.com"
    mailer_layout: "mailer"

  host: "http://localhost:3000"
  digit_50: 50

  microposts:
    image_content_types:
      - image/jpeg
      - image/gif
      - image/png
    image_accept_format: "image/jpeg,image/gif,image/png"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
