defaults: &defaults
  rails_tutorial:
    homepage_url: "http://www.railstutorial.org/"
    help_url: "http://www.railstutorial.org/help"
    book_url: "http://www.railstutorial.org/book"

  mailer:
    email_from_address: "noreply@example.com"
    mailer_layout: "mailer"

  host: "http://localhost:3000"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
